/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import static java.time.zone.ZoneRulesProvider.refresh;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author caiof
 */
public class CadastroCli_GUI extends javax.swing.JFrame {
    static String nome;
    static long cpf;
    static long cel;
    static long telfx;
    static String obs;
    
    String url = "jdbc:mysql://localhost:3306/mercadopedreira"; // enderço do BD
    String username = "root";        //nome de um usuário de seu BD
    String password = "root";  // senha do BD

    /**
     * Creates new form CadastroCli_GUI
     */
    public CadastroCli_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        telfxp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cpfp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nomep = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        celp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        obsp = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        buttonIcon1 = new org.edisoncor.gui.button.ButtonIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/teladefundomp.png"))); // NOI18N
        panelImage1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO CLIENTE:");
        panelImage1.add(jLabel1);
        jLabel1.setBounds(160, 10, 260, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("TEL. FIXO:");
        panelImage1.add(jLabel3);
        jLabel3.setBounds(20, 210, 100, 20);

        telfxp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telfxpActionPerformed(evt);
            }
        });
        panelImage1.add(telfxp);
        telfxp.setBounds(20, 230, 150, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("CPF:");
        panelImage1.add(jLabel4);
        jLabel4.setBounds(20, 110, 80, 20);

        cpfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfpActionPerformed(evt);
            }
        });
        panelImage1.add(cpfp);
        cpfp.setBounds(20, 130, 150, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("NOME:");
        panelImage1.add(jLabel6);
        jLabel6.setBounds(20, 60, 80, 20);

        nomep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomepActionPerformed(evt);
            }
        });
        panelImage1.add(nomep);
        nomep.setBounds(20, 80, 360, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("OBS:");
        panelImage1.add(jLabel9);
        jLabel9.setBounds(410, 60, 140, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("CEL:");
        panelImage1.add(jLabel12);
        jLabel12.setBounds(20, 160, 80, 20);

        celp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celpActionPerformed(evt);
            }
        });
        panelImage1.add(celp);
        celp.setBounds(20, 180, 150, 20);

        obsp.setColumns(20);
        obsp.setRows(5);
        jScrollPane1.setViewportView(obsp);

        panelImage1.add(jScrollPane1);
        jScrollPane1.setBounds(410, 80, 170, 96);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("CADASTRAR");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255), new java.awt.Color(51, 51, 51), new java.awt.Color(204, 204, 204)));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelImage1.add(jButton1);
        jButton1.setBounds(420, 340, 160, 40);

        buttonIcon1.setBackground(new java.awt.Color(255, 255, 255));
        buttonIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/voltar.png"))); // NOI18N
        buttonIcon1.setText("buttonIcon1");
        buttonIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIcon1ActionPerformed(evt);
            }
        });
        panelImage1.add(buttonIcon1);
        buttonIcon1.setBounds(20, 330, 60, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(600, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void telfxpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telfxpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telfxpActionPerformed

    private void cpfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfpActionPerformed

    private void nomepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomepActionPerformed

    private void celpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Controller.ConectaDriver_DB.carregaDriver();
        nome = nomep.getText();
        cpf = Long.valueOf(cpfp.getText());
        cel = Long.valueOf(celp.getText());
        telfx = Long.valueOf(telfxp.getText());
        obs = obsp.getText();

        try {

            Connection con = null;

            try {
                con = (Connection)DriverManager.getConnection(url, username, password);
            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, "ERRO S002 - Usuario, senha ou endereço errados");

            }

            // Recebendo os dados a serem inseridos na tabela
            String sql = "INSERT INTO cliente(cli_nome, cli_cpf , cli_cel, cli_tel, cli_obs) values('"+nome+"','"+cpf+"','"+cel+"','"+telfx+"','"+obs+"')";

            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement)con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção

                JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso!!!\n","",-1);
                nomep.setText("");
                cpfp.setText("");
                celp.setText("");
                telfxp.setText("");
                obsp.setText("");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na inserção!","ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Tratamento de erro caso o usuario não digite o telefone corretamente
            JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
            celp.setText("");
            telfxp.setText("");
        }

        refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIcon1ActionPerformed
        new Menu_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonIcon1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCli_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCli_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCli_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCli_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCli_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonIcon buttonIcon1;
    private javax.swing.JTextField celp;
    private javax.swing.JTextField cpfp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomep;
    private javax.swing.JTextArea obsp;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JTextField telfxp;
    // End of variables declaration//GEN-END:variables
}
