/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import static java.time.zone.ZoneRulesProvider.refresh;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caiof
 */
public class CAE_GUI extends javax.swing.JFrame {
    static String nome;
    static long cpf;
    static long cel;
    static long telfx;
    static String obs;
    
    String url = "jdbc:mysql://localhost:3306/mercadopedreira"; // enderço do BD
    String username = "root";        //nome de um usuário de seu BD
    String password = "root";  // senha do BD

    /**
     * Creates new form CAE_GUI
     */
    public CAE_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        telfxp2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cpfp2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nomep2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cel1p2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        obsp2 = new javax.swing.JTextArea();
        buttonIcon1 = new org.edisoncor.gui.button.ButtonIcon();
        buttonIcon2 = new org.edisoncor.gui.button.ButtonIcon();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/teladefundomp.png"))); // NOI18N
        panelImage1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTAR / ALTERAR / EXCUIR ");
        panelImage1.add(jLabel1);
        jLabel1.setBounds(100, 10, 410, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("TEL. FIXO:");
        panelImage1.add(jLabel3);
        jLabel3.setBounds(230, 150, 100, 20);

        telfxp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telfxp2ActionPerformed(evt);
            }
        });
        panelImage1.add(telfxp2);
        telfxp2.setBounds(230, 170, 150, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("CPF:");
        panelImage1.add(jLabel4);
        jLabel4.setBounds(10, 50, 80, 20);

        cpfp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfp2ActionPerformed(evt);
            }
        });
        panelImage1.add(cpfp2);
        cpfp2.setBounds(10, 70, 150, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("NOME:");
        panelImage1.add(jLabel6);
        jLabel6.setBounds(230, 50, 80, 20);

        nomep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomep2ActionPerformed(evt);
            }
        });
        panelImage1.add(nomep2);
        nomep2.setBounds(230, 70, 360, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("OBS:");
        panelImage1.add(jLabel9);
        jLabel9.setBounds(230, 200, 140, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("CEL:");
        panelImage1.add(jLabel12);
        jLabel12.setBounds(230, 100, 80, 20);

        cel1p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cel1p2ActionPerformed(evt);
            }
        });
        panelImage1.add(cel1p2);
        cel1p2.setBounds(230, 120, 150, 20);

        obsp2.setColumns(20);
        obsp2.setRows(5);
        jScrollPane1.setViewportView(obsp2);

        panelImage1.add(jScrollPane1);
        jScrollPane1.setBounds(230, 220, 170, 96);

        buttonIcon1.setBackground(new java.awt.Color(255, 255, 255));
        buttonIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/voltar.png"))); // NOI18N
        buttonIcon1.setText("buttonIcon1");
        buttonIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIcon1ActionPerformed(evt);
            }
        });
        panelImage1.add(buttonIcon1);
        buttonIcon1.setBounds(20, 340, 60, 50);

        buttonIcon2.setBackground(new java.awt.Color(255, 255, 255));
        buttonIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/lupa (1).png"))); // NOI18N
        buttonIcon2.setText("buttonIcon2");
        buttonIcon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIcon2ActionPerformed(evt);
            }
        });
        panelImage1.add(buttonIcon2);
        buttonIcon2.setBounds(170, 60, 40, 40);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("EXCLUIR");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255), new java.awt.Color(51, 51, 51), new java.awt.Color(204, 204, 204)));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelImage1.add(jButton1);
        jButton1.setBounds(20, 170, 130, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("ALTERAR");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255), new java.awt.Color(51, 51, 51), new java.awt.Color(204, 204, 204)));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelImage1.add(jButton2);
        jButton2.setBounds(20, 120, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(600, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void telfxp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telfxp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telfxp2ActionPerformed

    private void cpfp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfp2ActionPerformed

    private void nomep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomep2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomep2ActionPerformed

    private void cel1p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cel1p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cel1p2ActionPerformed

    private void buttonIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIcon1ActionPerformed
        new Menu_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonIcon1ActionPerformed

    private void buttonIcon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIcon2ActionPerformed
        try{     //Iniciando o possivel tratamento de erros
            //Declarando a variavel código
            long codigo = Long.valueOf(cpfp2.getText());
            Controller.ConectaDriver_DB.carregaDriver();// Carregando o driver
            try {// Tratamento de erro para a conexao
                // Declarando  a variavel de conexão con
                // e estabelendo a conexão
                Connection con = null;

                try {
                    con = (Connection) DriverManager.getConnection(url, username, password);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,"FLHA NA CONEXÃO");
                }

                // Declarando uma string com o comando mySQL para consulta
                String sql = "SELECT cli_nome, cli_cel, cli_tel, cli_obs FROM cliente where cli_cpf = "+codigo;
                // Criando variavel que executara o comando da string sql
                Statement stm = (Statement) con.createStatement();
                try//Tratamento de erro da consulta
                { //Criando variavel que exibira os resultados
                    //Executando o comando da string sql na variavel rs
                    ResultSet rs = stm.executeQuery(sql);

                    int i=0; // Variavel utilizada para saber se ha dados cadastrados

                    while (rs.next()) {  // Criando variaveis que receberão os valores do banco de dados
                        String nomet = rs.getString("cli_nome");
                        String cel1t = rs.getString("cli_cel");
                        String telfxt = rs.getString("cli_tel");
                        String obst = rs.getString("cli_obs");

                        i++;

                        nomep2.setText(String.valueOf(nomet));
                        cel1p2.setText(String.valueOf(cel1t));
                        telfxp2.setText(String.valueOf(telfxt));
                        obsp2.setText(String.valueOf(obst));

                    }

                    if(i==0){ // Verificando se ha dados cadastrados atraves da variavel i

                        JOptionPane.showMessageDialog(null,"Dado não cadastrado","Resultado",-1);

                    }

                } catch (Exception ex) { // Consulta mal sucedida
                    JOptionPane.showMessageDialog(null,"\nErro ao consultar!","ERRO",0);
                }

            } catch (SQLException ex) {
                // Conexão com servidor mal sucedida
                JOptionPane.showMessageDialog(null,"Erro ao conectar com o servidor","ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Código fora do formato
            JOptionPane.showMessageDialog(null,"Digite o código corretamante","ERRO",0);
            cpfp2.setText("");
        }
    }//GEN-LAST:event_buttonIcon2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        long codigo = Long.valueOf(cpfp2.getText()); // Recebendo o código
        try {// Tratamento de erro para a conexao
            // Declarando  a variavel de conexão con
            // e estabelendo a conexão
            Connection con = null;

            try {
                con = (Connection) DriverManager.getConnection(url, username, password);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "ERRO06 - Sem conexão");
            }

            // Criando String com comando SQL para exclusão
            String sql = "DELETE FROM cliente WHERE cli_cpf = "+cpfp2.getText();

            try // Tratamento de erros para exclusão
            {// Criando Variavel para executar a ação
                PreparedStatement excluir = (PreparedStatement) con.prepareStatement(sql);
                excluir.execute();// Executando a exclusão

                JOptionPane.showMessageDialog(null,"\nExclusão realizada com sucesso!!!\n","",-1);
                cpfp2.setText("");
                nomep2.setText("");
                cel1p2.setText("");
                telfxp2.setText("");
                obsp2.setText("");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na exclusão!","ERRO!",0);
            }

        } catch(NumberFormatException erro){ // Codigo digitado com caracteres não numericos
            JOptionPane.showMessageDialog(null,"Digite o código corretamante","ERRO",0);
            cpfp2.setText("");
        }
        refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //inicio
        nome = nomep2.getText();
        cel = Long.valueOf(cel1p2.getText());
        telfx = Long.valueOf(telfxp2.getText());
        obs = obsp2.getText();

        try {
            Connection con = null;
            try {
                con = (Connection) DriverManager.getConnection(url, username, password);
            }catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "ERRO 05 - Erro de conexão");
            }
            String sql = "UPDATE cliente SET cli_nome='"+nome+"',cli_cel='"+cel+"',cli_tel='"+telfx+"',cli_obs='"+obs+"' WHERE cli_cpf="+cpfp2.getText();
            //paci_nome, paci_rg, paci_sexo , paci_DDN, paci_conv, paci_end,paci_cep , paci_email , paci_cel1, paci_cel2, paci_tel1, paci_obs

            try {
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção

                JOptionPane.showMessageDialog(null,"\nAlteração realizada com sucesso!!!\n","",-1);
                nomep2.setText("");
                cpfp2.setText("");
                cel1p2.setText("");
                telfxp2.setText("");
                obsp2.setText("");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na alteração!","ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Tratamento de erro caso o usuario não digite o telefone corretamente
            JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
            cel1p2.setText("");
            telfxp2.setText("");
        }
        refresh();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAE_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAE_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAE_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAE_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAE_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonIcon buttonIcon1;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon2;
    private javax.swing.JTextField cel1p2;
    private javax.swing.JTextField convp2;
    private javax.swing.JTextField convp3;
    private javax.swing.JTextField cpfp2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomep2;
    private javax.swing.JTextArea obsp2;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JTextField telfxp2;
    // End of variables declaration//GEN-END:variables
}
